# Site settings
title: Ryan Tanay
email: rtanay@gmail.com
description: Full Stack Developer Portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ryantanay.com" # the base hostname & protocol for your site
twitter_username: RyanTanay
github_username:  NewEvolution

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /posts/:title